services:
  casal_ginebro:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        AUTORUN_ENABLED: "false"
        APP_ENV: ${APP_ENV}
    container_name: ${APP_HOSTNAME}
    hostname: ${APP_HOSTNAME}
    environment:
      PUID: 1000
      SSL_MODE: 'mixed'
    ports:
      - '8080:80'
      - '8180:443'
    volumes:
      - ./:/var/www/html
    networks:
      - casal_ginebro
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost || exit 1"]
      interval: 5m
      timeout: 3s
      retries: 3
      
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 2000:3306
    networks:
      - casal_ginebro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_casal_ginebro
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - casal_ginebro
    depends_on:
      - mysql

networks:
  casal_ginebro:
    external: true
